version: "3" 
services:
    gitbook:
        image: zchkun/gitbook
        privileged: true
        tty: true
        ports:
            - 4000:4000
        volumes:
            - ./:/root
        command: gitbook serve
